# Form implementation generated from reading ui file 'playActionScreen.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayActionWindow(object):
    def setupUi(self, PlayActionWindow):
        PlayActionWindow.setObjectName("PlayActionWindow")
        PlayActionWindow.resize(708, 500)
        self.centralwidget = QtWidgets.QWidget(PlayActionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(220, 140, 251, 181))
        self.textEdit.setObjectName("textEdit")
        PlayActionWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PlayActionWindow)
        self.statusbar.setObjectName("statusbar")
        PlayActionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlayActionWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayActionWindow)

    def retranslateUi(self, PlayActionWindow):
        _translate = QtCore.QCoreApplication.translate
        PlayActionWindow.setWindowTitle(_translate("PlayActionWindow", "Play Action Window"))
