# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timerScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, TimerWindow):
        TimerWindow.setObjectName("TimerWindow")
        TimerWindow.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.centralwidget = QtWidgets.QWidget(TimerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(275, 300, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 380, 75, 23))
        self.pushButton.setObjectName("pushButton")
        TimerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TimerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        TimerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TimerWindow)
        self.statusbar.setObjectName("statusbar")
        TimerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TimerWindow)
        QtCore.QMetaObject.connectSlotsByName(TimerWindow)

    def retranslateUi(self, TimerWindow):
        _translate = QtCore.QCoreApplication.translate
        TimerWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Stop Timer"))
